---
require:
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - _snippets/*

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*
    - Rakefile
    - app/controllers/**/*

Security/YAMLLoad:
  Enabled: true
  Exclude:
    - spec/**/*

Style/HashSyntax:
  Enabled: true
  Exclude:
    - Rakefile

Style/SymbolArray:
  Enabled: true
  Exclude:
    - db/migrations/**/*
    - Rakefile

Style/Documentation:
  Enabled: true
  Exclude:
    - app/forms/**/*

Style/OpenStructUse:
  Enabled: true
  Exclude:
    - app/models/**/*

Metrics/ClassLength:
  Enabled: true
  Exclude:
    - app/controllers/**/*